### ISSUE TITLE
Ist es hier notwendig zu bestimmen, ob die Daten metrisch sind ?

### ISSUE THREAD

**Issue by yiyi808** [yiyi808/wissArbeiten_2122_Gruppe_11#11]
Ist es hier notwendig zu bestimmen, ob die Daten metrisch sind ?

_Originally posted by @yiyi808 in https://github.com/yiyi808/wissArbeiten_2122_Gruppe_11/pull/10#discussion_r798865061_

**Comment by Haiyi11** [comment]
Ja klar, deine Idee ist richtig

**Comment by yiyi808** [comment]
Alles klar.

**Comment by Xinyi-Jing** [comment]
Ich denke, bei der vierten Aufgabe ist es notwendig, zuerst die Art der Variablen zu bestimmen.
