### ISSUE TITLE
Termine für Teil 5

### ISSUE THREAD

**Issue by Haiyi11** [yiyi808/wissArbeiten_2122_Gruppe_11#19]
Hallo, wann wird Teil 5 der Diskussion stattfinden?

**Comment by Xinyi-Jing** [comment]
Wenn Jinzhen und ich Aufgabe vier erledigt haben, werden wir Sie und Yi erneut kontaktieren.

**Comment by LJinzhen** [comment]
Xinyi und ich werden den Teil 4 abschließen und bald darauf mit dem Teil 5 beginnen können.
