### ISSUE TITLE
to Yi

### ISSUE THREAD

**Issue by Haiyi11** [yiyi808/wissArbeiten_2122_Gruppe_11#2]
Ich habe deinen Code gelesen und meine Vorschläge sind in deinem Code enthalten. Können wir das morgen besprechen, wenn du ihn fertig gelesen hast?

Haiyi

**Comment by yiyi808** [comment]
Alles klar. Ich lesen deine Code jetzt.

**Comment by yiyi808** [comment]
Ich habe gesehen, ich habe Aufgabe 3), 4) und 5) nicht gut verstanden. 
Können wir morgen diskutieren?

**Comment by Haiyi11** [comment]
Okay, können wir uns morgen um 14 Uhr in der Bibliothek treffen? Bring deinen Laptop mit.

**Comment by yiyi808** [comment]
Okay, das passt. Bis morgen!
