### ISSUE TITLE
Aufgabe 4

### ISSUE THREAD

**Issue by Xinyi-Jing** [yiyi808/wissArbeiten_2122_Gruppe_11#22]
Hallo, Jinzhen .Wir können besprechen, wie Aufgaben verteilt werden.

**Comment by LJinzhen** [comment]
Ich denke, wir können das gemeinsam besprechen, nachdem jeder von uns eine Frage geschrieben hat。

**Comment by Xinyi-Jing** [comment]
Wir schreiben jeder zuerst auf, was wir verstanden haben, und wiederholen es dann gemeinsam.
