### ISSUE TITLE
Korrigiert R-Code

### ISSUE THREAD

**Issue by yiyi808** [yiyi808/wissArbeiten_2122_Gruppe_11#3]
Ich habe meinen R-Code wie besprochen korrigiert. Du kannst meine überarbeitete Version durchgehen.
Während dieser Zeit habe ich neue Probleme gefunden, bei den Fragen 3 und 4 ist Ihr Verständnis in der Tat richtig, aber wir haben unterschiedliche Vorstellungen über die Zusammenhang.
In Frage 5 glaube ich nicht, dass du die dichotome Variablen genutzt haben. Es soll nicht nur einfach "Ja/Nein" Variable sein. 
*Mathe-LK ist eine mathmatische Kurs in der Schule. Es ist gar nicht wichtig.

**Comment by Haiyi11** [comment]
OK, lass uns das morgen gemeinsam besprechen und den endgültigen Code bestätigen. Morgen um 14 Uhr in der Bibliothek?

**Comment by yiyi808** [comment]
Okay, bis morgen😊
