### ISSUE TITLE
plot Diskussion 

### ISSUE THREAD

**Issue by LJinzhen** [yiyi808/wissArbeiten_2122_Gruppe_11#30]
Hallo, ich werde morgen Teil c) zeichnen, hast du Zeit und wir können es besprechen.

**Comment by Xinyi-Jing** [comment]
Okay.  Ich werde mir heute Abend Ihre neue Zeichnung ansehen und eine Beschreibung der Analyse hinzufügen. Dann werden wir morgen gemeinsam den neuen Abschnitt besprechen.
