### ISSUE TITLE
Für Teil 3

### ISSUE THREAD

**Issue by yiyi808** [yiyi808/wissArbeiten_2122_Gruppe_11#6]
Ich habe gesehen, dass wir alle einen R-Code für Teil 3 hochgeladen haben.

Ich bin mir nicht sicher, ob ich es richtig gemacht habe. In e) und f) weiß ich nicht, wie ich die Funktionen schreiben soll. 

Ich stelle fest, dass es viele Unterschiede in unseren R-Codes gibt.
Können wir das morgen gemeinsam diskutieren?

**Comment by Haiyi11** [comment]
OK

**Comment by Xinyi-Jing** [comment]
Wir können den Code in eine Datei einfügen und gemeinsam korrigieren.
